### ISSUE TITLE
Nutrients doesn't decrease when player just staying and walking

### ISSUE THREAD

**Issue by LickPACH2** [dannydjdk/Nutritional-Balance#32]
When I run or jump, nutrients are decrease.
But I dont run or jump, nutrients barely decrease. I want to make them decrease

**Comment by dannydjdk** [comment]
This is intended and the only way the system would work. Nutritional Balance uses the same system that Minecraft hunger uses. As you burn saturation and hunger points, you burn nutrients. As you gain hunger and saturation points, you gain nutrients. Otherwise, you would lose nutrients but not be able to eat and eventually end up malnourished.
