### ISSUE TITLE
Inventory button

### ISSUE THREAD

**Issue by AK-Chester** [dannydjdk/Nutritional-Balance#4]
Not a bug ... just a feature request: The nutrient button overlaps with the one from charm's portable crafting. Could you add a config option to turn that button off? The 'n' key alone would be enough for me. Nice mod btw!

**Comment by dannydjdk** [comment]
Thanks for the suggestion! Next version will have a client config option to disable and/or move the nutrient button.

I'd recommend moving it rather than disabling it if other players will play your pack. One of the functions of the button, besides convenience, is alerting players to the fact that the mod is installed and that they need to watch their nutrients.

**Comment by dannydjdk** [comment]
Released with version 1.16.5-0.7.4

**Comment by AK-Chester** [comment]
Thanks a lot! Works like a "charm".
