### ISSUE TITLE
Milk Cannot Have Nutrition

### ISSUE THREAD

**Issue by definitelynotstarlord** [dannydjdk/Nutritional-Balance#40]
Nutritional Balance 5.1.3
Forge 47.3.0
Mod list: https://pastebin.com/s1Uwn1gJ

I am putting together a little family modpack and was adding in food with missing nutritional data. I see that the `#forge:milk` tag is already added for protein, but yet the `milk_bucket` or `milk_bottle` are not assigned as protein. Adding the items do not work either. 

This is likely a conflict with one of my other mods but thought I'd add the issue.

**Comment by dannydjdk** [comment]
This is by design, because milk is technically not a food. The benefit of milk being tagged as protein is that any foods  crafted with milk will contain protein.

The problem with milk is that it does not provide saturation or hunger points, and the nutrients are based on these values. Also, it is not necessary to be hungry to consume milk. Therefore, if it did provide nutrient points, you could just drink milk until your protein is in balance and bypass the game mechanics.

I do appreciate you taking the time to create the issue though.
