### ISSUE TITLE
Debuffs won't go away (visual only)

### ISSUE THREAD

**Issue by hedgyeverwonder** [dannydjdk/Nutritional-Balance#6]
Not sure if it's a bug or if there's a way to fix it in game but when nutritional values dip below or go above the red lines and the debuffs appear they never go away even if the nutrient values are eventually balanced

**Comment by dannydjdk** [comment]
This would definitely be a bug, but not one I am able to reproduce. Could you send me a copy of your world? More specifically, I'd like to see your playerdata file. Also, if you could post a screenshot of your nutrients, that would be helpful too.

**Comment by dannydjdk** [comment]
I believe I was finally able to reproduce this, except that the issue was only visual. After the nutrients were balanced, the effects counted down to 0:00, then stayed there. The affect actually wasn't applied to the player, but the icons still lingered. Leaving and rejoining the game fixed it. Since the problem is intermittent, it will be challenging to troubleshoot, but I have a place to start now.
